### ISSUE TITLE
dependency error with version 1.07

### ISSUE THREAD

**Issue by glasswalk3r** [lucastheisen/ipc-open3-callback#10]
From a brand new Perlbrew install:

cpan[1]> install IPC::Open3::Callback
Database was generated on Sun, 08 Dec 2013 12:30:30 GMT

Running install for module 'IPC::Open3::Callback'
Running make for L/LT/LTHEISEN/IPC-Open3-Callback-1.07.tar.gz
Fetching with LWP:
http://cpan.kinghost.net/authors/id/L/LT/LTHEISEN/IPC-Open3-Callback-1.07.tar.gz
Fetching with LWP:
http://cpan.kinghost.net/authors/id/L/LT/LTHEISEN/CHECKSUMS
Checksum for /home/arfreitas/.cpan/sources/authors/id/L/LT/LTHEISEN/IPC-Open3-Callback-1.07.tar.gz ok
Scanning cache /home/arfreitas/.cpan/build for sizes
............................................................................DONE

  CPAN.pm: Building L/LT/LTHEISEN/IPC-Open3-Callback-1.07.tar.gz

CPAN::Reporter not installed.  No reports will be sent.
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for IPC::Open3::Callback
Writing MYMETA.yml and MYMETA.json
cp lib/IPC/Open3/Callback/CommandRunner.pm blib/lib/IPC/Open3/Callback/CommandRunner.pm
cp lib/IPC/Open3/Callback/Command.pm blib/lib/IPC/Open3/Callback/Command.pm
cp lib/IPC/Open3/Callback.pm blib/lib/IPC/Open3/Callback.pm
AutoSplitting blib/lib/IPC/Open3/Callback.pm (blib/lib/auto/IPC/Open3/Callback)
Manifying blib/man3/IPC::Open3::Callback.3
Manifying blib/man3/IPC::Open3::Callback::Command.3
Manifying blib/man3/IPC::Open3::Callback::CommandRunner.3
  LTHEISEN/IPC-Open3-Callback-1.07.tar.gz
  /usr/bin/make -j4 -j4 -- OK
Running make test
PERL_DL_NONLAZY=1 /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/author-critic.t ........... skipped: these tests are for testing by the author
t/Callback.t ................ Can't locate Class/Accessor.pm in @INC (you may need to install the Class::Accessor module) (@INC contains: /home/arfreitas/.cpan/build/IPC-Open3-Callback-1.07-ka8Dax/blib/lib /home/arfreitas/.cpan/build/IPC-Open3-Callback-1.07-ka8Dax/blib/arch /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/lib /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/t /home/arfreitas/Projetos/siebel-monitoring-tools/Nagios/Nagios-Plugin-Siebel-Srvrmgr/lib /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/lib /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/t /home/arfreitas/Projetos/siebel-monitoring-tools/Nagios/Nagios-Plugin-Siebel-Srvrmgr/lib /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/site_perl/5.18.1/x86_64-linux /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/site_perl/5.18.1 /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/5.18.1/x86_64-linux /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/5.18.1 .) at /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/5.18.1/parent.pm line 20.
BEGIN failed--compilation aborted at /home/arfreitas/.cpan/build/IPC-Open3-Callback-1.07-ka8Dax/blib/lib/IPC/Open3/Callback.pm line 44.
Compilation failed in require at t/Callback.t line 4.
BEGIN failed--compilation aborted at t/Callback.t line 4.
# Looks like your test exited with 2 before it could output anything.
t/Callback.t ................ Dubious, test returned 2 (wstat 512, 0x200)
Failed 16/16 subtests 
t/Callback_Command.t ........ ok     
t/Callback_CommandRunner.t .. Can't locate Test/Most.pm in @INC (you may need to install the Test::Most module) (@INC contains: /home/arfreitas/.cpan/build/IPC-Open3-Callback-1.07-ka8Dax/blib/lib /home/arfreitas/.cpan/build/IPC-Open3-Callback-1.07-ka8Dax/blib/arch /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/lib /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/t /home/arfreitas/Projetos/siebel-monitoring-tools/Nagios/Nagios-Plugin-Siebel-Srvrmgr/lib /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/lib /home/arfreitas/Projetos/siebel-monitoring-tools/Siebel-Srvrmgr/t /home/arfreitas/Projetos/siebel-monitoring-tools/Nagios/Nagios-Plugin-Siebel-Srvrmgr/lib /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/site_perl/5.18.1/x86_64-linux /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/site_perl/5.18.1 /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/5.18.1/x86_64-linux /home/arfreitas/perl5/perlbrew/perls/perl-5.18.1/lib/5.18.1 .) at t/Callback_CommandRunner.t line 4.
BEGIN failed--compilation aborted at t/Callback_CommandRunner.t line 4.
t/Callback_CommandRunner.t .. Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
t/release-pod-coverage.t .... skipped: these tests are for release candidate testing
t/release-pod-syntax.t ...... skipped: these tests are for release candidate testing

Test Summary Report
-------------------
t/Callback.t              (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
t/Callback_CommandRunner.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=6, Tests=13,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.06 cusr  0.03 csys =  0.12 CPU)
Result: FAIL
Failed 2/6 test programs. 0/13 subtests failed.
make: ** [test_dynamic] Erro 255
  LTHEISEN/IPC-Open3-Callback-1.07.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports LTHEISEN/IPC-Open3-Callback-1.07.tar.gz
Running make install
  make test had returned bad status, won't install without force
Stopping: 'install' failed for 'IPC::Open3::Callback'.
Failed during this command:
 LTHEISEN/IPC-Open3-Callback-1.07.tar.gz      : make_test NO

**Comment by lucastheisen** [comment]
Missing test dependency, resolved with push [536f0e3](https://github.com/lucastheisen/ipc-open3-callback/commit/536f0e3e5e4768378c516ecef1b8c71e6e047c2f)
